import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, FileSearch, Link2, Loader2, Plus, Save, Send, Sparkles, Trash2, X } from 'lucide-react';
import { creatorService, type Material, type Platform, type Topic, type Work } from '../../services/creator';

const statuses = [['idea','想法'],['preparing','准备中'],['writing','写作中'],['ready','待发布'],['published','已发布'],['archived','归档']];
const platformLabel:Record<string,string>={zhihu:'知乎长文',xiaohongshu:'小红书图文',short_video:'短视频口播'};

export default function TopicWorkspace(){
 const {id}=useParams(); const nav=useNavigate(); const [topic,setTopic]=useState<Topic|null>(null); const [materials,setMaterials]=useState<any[]>([]); const [query,setQuery]=useState(''); const [active,setActive]=useState<Work|null>(null); const [content,setContent]=useState(''); const [busy,setBusy]=useState(''); const [issues,setIssues]=useState<any[]>([]); const [message,setMessage]=useState(''); const [loadError,setLoadError]=useState(''); const [preference,setPreference]=useState(''); const [pub,setPub]=useState({platform:'zhihu',url:'',notes:'',views:0,likes:0,favorites:0,comments:0});
 const load=useCallback(async()=>{if(!id)return;try{const t=await creatorService.getTopic(id);setTopic(t);setLoadError('');const main=t.works?.find(w=>w.platform==='zhihu')||t.works?.[0]||null;setActive(a=>a? t.works?.find(w=>w.id===a.id)||main:main);}catch(e:any){setLoadError(e.response?.data?.error||'选题加载失败')}},[id]);
 useEffect(()=>{load()},[load]); useEffect(()=>setContent(active?.content||''),[active?.id,active?.content]);
 const selected=useMemo(()=>new Set(topic?.materials?.map(m=>m.noteId)||[]),[topic?.materials]);
 const updateField=(key:keyof Topic,value:string)=>setTopic(t=>t?{...t,[key]:value}:t);
 const saveTopic=async()=>{if(!topic)return;setBusy('save-topic');try{await creatorService.updateTopic(topic.id,topic);setMessage('选题已保存');await load()}catch(e:any){setMessage(e.response?.data?.error||'保存失败')}finally{setBusy('')}};
 const search=async()=>{if(!query.trim())return;setBusy('search');try{setMaterials(await creatorService.retrieve(query))}finally{setBusy('')}};
 const add=async(noteId:string)=>{if(!topic)return;await creatorService.addMaterial(topic.id,noteId);await load()};
 const remove=async(noteId:string)=>{if(!topic)return;await creatorService.removeMaterial(topic.id,noteId);await load()};
 const generate=async()=>{if(!topic)return;setBusy('draft');setMessage('');try{const r=await creatorService.generateDraft(topic.id,[...selected]);setActive(r.work);setContent(r.work.content);setMessage(r.risks?.length?`草稿已生成，${r.risks.length} 项需要核实`:'草稿已生成并保存引用');await load()}catch(e:any){setMessage(e.response?.data?.error||'生成失败')}finally{setBusy('')}};
 const saveWork=async(status=active?.status||'draft')=>{if(!active)return;setBusy('save-work');try{const w=await creatorService.updateWork(active.id,{title:active.title,content,status,preference,preferenceConfirmed:!!preference.trim()});setActive({...active,...w});setPreference('');setMessage('作品和修改记录已保存');await load()}catch(e:any){setMessage(e.response?.data?.error||'作品保存失败')}finally{setBusy('')}};
 const review=async()=>{if(!active)return;await saveWork();setBusy('review');try{const r=await creatorService.reviewStyle(active.id);setIssues(r.issues||[])}finally{setBusy('')}};
 const transform=async(platform:Platform)=>{if(!active)return;await saveWork();setBusy(platform);try{const r=await creatorService.transform(active.id,platform);setActive(r.work);setContent(r.work.content);setMessage(`${platformLabel[platform]}已生成`);await load()}finally{setBusy('')}};
 const publish=async()=>{if(!active||!pub.url)return;setBusy('publish');try{await creatorService.createPublication({workId:active.id,...pub,publishedAt:new Date().toISOString()});setPub({...pub,url:'',notes:''});setMessage('发布记录已保存');await load()}catch(e:any){setMessage(e.response?.data?.error||'发布记录保存失败')}finally{setBusy('')}};
 if(loadError)return <div style={{padding:40}}><p>{loadError}</p><button className="btn btn-outline" onClick={()=>nav('/')}><ArrowLeft size={16}/>返回工作台</button> <button className="btn btn-primary" onClick={load}>重试</button></div>;
 if(!topic)return <div style={{padding:40}}><Loader2 className="animate-spin"/> 加载选题...</div>;
 return <div style={{height:'100vh',display:'grid',gridTemplateColumns:'280px minmax(480px,1fr) 340px',background:'var(--bg-primary)'}}>
  <aside style={{borderRight:'1px solid var(--border-color)',padding:20,overflowY:'auto'}}><button className="btn" style={{background:'transparent'}} onClick={()=>nav('/')}><ArrowLeft size={16}/> 工作台</button><h2 style={{fontSize:18}}>选题信息</h2><Field label="选题标题" value={topic.title} onChange={v=>updateField('title',v)}/><Field label="核心问题 *" area value={topic.coreQuestion} onChange={v=>updateField('coreQuestion',v)}/><Field label="目标读者 *" area value={topic.targetAudience} onChange={v=>updateField('targetAudience',v)}/><Field label="明确结论 *" area value={topic.conclusion} onChange={v=>updateField('conclusion',v)}/><Field label="读完后的行动或认识 *" area value={topic.desiredAction} onChange={v=>updateField('desiredAction',v)}/><label style={labelStyle}>状态</label><select value={topic.status} onChange={e=>updateField('status',e.target.value)} style={inputStyle}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="btn btn-primary" style={{width:'100%',marginTop:12}} onClick={saveTopic} disabled={!!busy}><Save size={15}/>保存选题</button>
  <h3 style={{fontSize:15,marginTop:26}}>已选素材（{selected.size}）</h3>{topic.materials?.map(m=><div key={m.noteId} style={{padding:'10px 0',borderBottom:'1px solid var(--border-color)',fontSize:13}}><div style={{display:'flex',justifyContent:'space-between'}}><button onClick={()=>nav(`/editor/${m.noteId}`)} style={{border:0,background:'none',color:'inherit',textAlign:'left',cursor:'pointer'}}>{m.note?.title||'素材'}</button><button onClick={()=>remove(m.noteId)} style={{border:0,background:'none',cursor:'pointer',color:'var(--text-tertiary)'}}><X size={14}/></button></div></div>)}</aside>
  <main style={{display:'flex',flexDirection:'column',minWidth:0}}><div style={{padding:'15px 24px',borderBottom:'1px solid var(--border-color)',display:'flex',gap:8,alignItems:'center'}}><select value={active?.id||''} onChange={e=>{const w=topic.works?.find(x=>x.id===e.target.value)||null;setActive(w)}} style={{...inputStyle,maxWidth:220}}><option value="">尚未生成作品</option>{topic.works?.map(w=><option key={w.id} value={w.id}>{platformLabel[w.platform]} · {w.title||'未命名'}</option>)}</select><div style={{flex:1}}/>{active&&<><button className="btn btn-outline" onClick={()=>saveWork()} disabled={!!busy}><Save size={15}/>保存</button><button className="btn btn-primary" onClick={()=>saveWork('ready')} disabled={!!busy}><CheckCircle2 size={15}/>标为待发布</button></>}</div>
  {active?<><input value={active.title} onChange={e=>setActive({...active,title:e.target.value})} placeholder="作品标题" style={{margin:'28px 44px 8px',fontSize:28,fontWeight:750,border:0,background:'transparent',outline:'none',color:'inherit'}}/><textarea value={content} onChange={e=>setContent(e.target.value)} style={{flex:1,margin:'0 44px 30px',padding:0,border:0,resize:'none',outline:'none',fontSize:16,lineHeight:1.9,background:'transparent',color:'inherit'}}/></>:<div style={{margin:'auto',textAlign:'center',maxWidth:420,color:'var(--text-secondary)'}}><Sparkles size={42} style={{color:'#10b981'}}/><h2>从你的素材开始写</h2><p>先补齐左侧四项信息，再从右侧找到并固定素材。生成的私人事实都会保留来源。</p><button className="btn btn-primary" onClick={generate} disabled={busy==='draft'||selected.size===0}>{busy==='draft'?<Loader2 className="animate-spin"/>:<PenIcon/>}生成知乎草稿</button></div>}
  {message&&<div style={{padding:'10px 24px',background:'#ecfdf5',color:'#047857',fontSize:13}}>{message}</div>}</main>
  <aside style={{borderLeft:'1px solid var(--border-color)',padding:20,overflowY:'auto'}}><h2 style={{fontSize:18}}>创作助手</h2><div style={{display:'flex',gap:6}}><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="查找历史素材" style={{...inputStyle,flex:1}}/><button className="btn btn-outline" onClick={search}><FileSearch size={15}/></button></div>{materials.map((r:any)=><div key={r.id} style={{padding:'12px 0',borderBottom:'1px solid var(--border-color)'}}><div style={{fontWeight:600,fontSize:13}}>{r.title}</div><div style={{fontSize:11,color:'#059669',margin:'5px 0'}}>{r.reason}</div><p style={{fontSize:12,color:'var(--text-secondary)',maxHeight:48,overflow:'hidden'}}>{r.contentText}</p><button className="btn btn-outline" style={{padding:'5px 9px',fontSize:11}} disabled={selected.has(r.id)} onClick={()=>add(r.id)}><Plus size={12}/>{selected.has(r.id)?'已选择':'加入选题'}</button></div>)}
  {active&&<><h3 style={{fontSize:15,marginTop:24}}>AI 操作</h3><button className="btn btn-outline" style={wideButton} onClick={review} disabled={!!busy}><Sparkles size={15}/>表达风格检查</button>{active.platform==='zhihu'&&<><button className="btn btn-outline" style={wideButton} onClick={()=>transform('xiaohongshu')} disabled={!!busy}>生成小红书图文</button><button className="btn btn-outline" style={wideButton} onClick={()=>transform('short_video')} disabled={!!busy}>生成短视频口播</button></>}<h3 style={{fontSize:15,marginTop:24}}>记住这次修改</h3><textarea value={preference} onChange={e=>setPreference(e.target.value)} placeholder="例如：以后开头直接说结论，不要铺垫" style={{...inputStyle,minHeight:60}}/><p style={{fontSize:11,color:'var(--text-tertiary)'}}>填写后，下次保存作品时会明确加入长期表达规则。</p>
  {issues.length>0&&<div style={{marginTop:12}}>{issues.map((x,i)=><div key={i} style={{padding:10,marginBottom:8,background:'var(--bg-input)',borderRadius:8,fontSize:12}}><b>{x.message}</b>{x.quote&&<div style={{color:'var(--text-tertiary)',margin:'5px 0'}}>“{x.quote}”</div>}<div>{x.suggestion}</div></div>)}</div>}
  <h3 style={{fontSize:15,marginTop:24}}>引用来源</h3>{active.citations?.length?<>{active.citations.map(c=><button key={c.id} onClick={()=>c.noteId&&nav(`/editor/${c.noteId}`)} style={{display:'block',width:'100%',textAlign:'left',padding:10,marginBottom:7,border:'1px solid var(--border-color)',borderRadius:8,background:'transparent',color:'inherit',cursor:c.noteId?'pointer':'default'}}><Link2 size={12}/> {c.marker} {c.sourceTitle||'模型补充'}<div style={{fontSize:11,color:'var(--text-tertiary)',marginTop:5}}>{c.sourceExcerpt}</div></button>)}</>:<p style={{fontSize:12,color:'var(--text-tertiary)'}}>当前版本没有可用引用。</p>}
  <h3 style={{fontSize:15,marginTop:24}}>登记发布</h3><select value={pub.platform} onChange={e=>setPub({...pub,platform:e.target.value})} style={inputStyle}><option value="zhihu">知乎</option><option value="xiaohongshu">小红书</option><option value="bilibili">B站</option><option value="douyin">抖音</option><option value="wechat_video">视频号</option></select><input value={pub.url} onChange={e=>setPub({...pub,url:e.target.value})} placeholder="作品链接" style={{...inputStyle,marginTop:7}}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,marginTop:7}}>{(['views','likes','favorites','comments'] as const).map(k=><input key={k} type="number" min="0" value={pub[k]} onChange={e=>setPub({...pub,[k]:Math.max(0,Number(e.target.value))})} placeholder={{views:'阅读',likes:'点赞',favorites:'收藏',comments:'评论'}[k]} style={inputStyle}/>)}</div><textarea value={pub.notes} onChange={e=>setPub({...pub,notes:e.target.value})} placeholder="效果和复盘备注" style={{...inputStyle,marginTop:7,minHeight:60}}/><button className="btn btn-primary" style={wideButton} onClick={publish} disabled={!pub.url||!!busy}><Send size={14}/>保存发布记录</button></>}</aside>
 </div>
}
function Field({label,value,onChange,area}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}){return <div style={{marginBottom:10}}><label style={labelStyle}>{label}</label>{area?<textarea value={value||''} onChange={e=>onChange(e.target.value)} style={{...inputStyle,minHeight:68,resize:'vertical'}}/>:<input value={value||''} onChange={e=>onChange(e.target.value)} style={inputStyle}/>}</div>}
function PenIcon(){return <Sparkles size={15}/>}
const labelStyle={display:'block',fontSize:11,color:'var(--text-secondary)',marginBottom:5} as const;
const inputStyle={width:'100%',padding:'9px 10px',border:'1px solid var(--border-color)',borderRadius:7,background:'var(--bg-input)',color:'inherit',boxSizing:'border-box'} as const;
const wideButton={width:'100%',justifyContent:'center',marginTop:7} as const;
