import { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { BookOpen, Download, Home, LogOut, Settings, SlidersHorizontal, Trash2, Upload } from 'lucide-react';
import { useAuthStore } from '../../stores/authStore';
import api from '../../services/api';
import SettingsModal from '../ui/SettingsModal';

export default function Sidebar(){
 const nav=useNavigate(), loc=useLocation(); const user=useAuthStore(s=>s.user), logout=useAuthStore(s=>s.logout); const [settings,setSettings]=useState(false); const [working,setWorking]=useState('');
 const importNotes=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setWorking('import');const form=new FormData();form.append('file',f);try{const r=await api.post('/notes/import',form);alert(`导入成功，共 ${r.data.count} 条素材`);nav('/materials')}finally{setWorking('')}};
 const exportAll=async()=>{setWorking('export');try{const r=await api.get('/notes/export',{responseType:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(r.data);a.download='Notavia_Export.zip';a.click();URL.revokeObjectURL(a.href)}finally{setWorking('')}};
 const items=[{path:'/',label:'创作工作台',icon:<Home size={17}/>},{path:'/materials',label:'素材库',icon:<BookOpen size={17}/>},{path:'/style-profile',label:'表达规则',icon:<SlidersHorizontal size={17}/>},{path:'/trash',label:'最近删除',icon:<Trash2 size={17}/>}];
 return <div style={{height:'100%',display:'flex',flexDirection:'column',padding:'22px 16px',boxSizing:'border-box',background:'var(--bg-panel)',borderRight:'1px solid var(--border-color)'}}><button onClick={()=>setSettings(true)} style={{display:'flex',alignItems:'center',gap:10,padding:10,border:0,background:'transparent',color:'inherit',cursor:'pointer',textAlign:'left'}}><span style={{width:32,height:32,borderRadius:9,display:'grid',placeItems:'center',background:'#d1fae5',color:'#047857',fontWeight:750}}>79</span><span><b style={{display:'block'}}>{user?.name||'七九'}</b><small style={{color:'var(--text-tertiary)'}}>私人内容工作台</small></span><Settings size={15} style={{marginLeft:'auto'}}/></button><div style={{marginTop:22,display:'grid',gap:5}}>{items.map(i=><button key={i.path} onClick={()=>nav(i.path)} style={{display:'flex',alignItems:'center',gap:10,padding:'10px 12px',border:0,borderRadius:8,background:loc.pathname===i.path?'var(--bg-panel-hover)':'transparent',color:'inherit',cursor:'pointer',fontWeight:550}}>{i.icon}{i.label}</button>)}</div><div style={{marginTop:'auto',display:'grid',gap:7}}><label className="btn btn-outline" style={{justifyContent:'center',cursor:'pointer'}}><Download size={14}/>{working==='import'?'导入中':'导入素材'}<input type="file" accept=".zip,.md,.txt,.markdown" hidden onChange={importNotes}/></label><button className="btn btn-outline" onClick={exportAll}><Upload size={14}/>{working==='export'?'导出中':'完整导出'}</button><button className="btn" onClick={logout} style={{background:'transparent',color:'var(--text-secondary)'}}><LogOut size={14}/>退出</button></div>{settings&&<SettingsModal isOpen onClose={()=>setSettings(false)}/>}</div>
}
